import { emailBrandHeader } from './email-brand.js';

const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
const publicPath = (locale, item) => `/${locale}/${item.type}/${encodeURIComponent(item.slug || item.id)}`;

// Only accepts the public homepage projection, never subscriptions, outbox, or digest snapshots.
export function renderPublicDigestPreview(discovery, locale = 'en') {
  locale = locale === 'zh' ? 'zh' : 'en';
  const zh = locale === 'zh', num = new Intl.NumberFormat(zh ? 'zh-CN' : 'en-US');
  const rows = discovery.items.slice(0, 3).map(item => {
    const chart = discovery.previewCharts?.find(chart => chart.type===item.type && chart.id===item.id && /^data:image\/png;base64,[A-Za-z0-9+/]+=*$/.test(chart.image));
    const chartHtml = chart ? `<figure style="margin:18px 0 0"><figcaption style="color:#666;font-size:12px">${item.metricScope==='associated-repository' ? (zh ? '关联仓库 · ' : 'Associated repository · ') : ''}${zh ? '累计新增 Star · 30 天' : 'Cumulative new Stars · 30 days'}</figcaption><img src="${escape(chart.image)}" alt="${escape(item.full_name)} · ${zh ? '30 天累计新增 Star 图表' : '30-day cumulative new Stars chart'}" width="544" style="display:block;width:100%;height:auto;margin-top:8px"><div style="display:flex;justify-content:space-between;color:#666;font-size:11px"><span>${escape(chart.start)}</span><span>${escape(chart.end)}</span></div></figure>` : '';
    const metric = item.gain == null ? '' : `${item.metricScope === 'associated-repository' ? (zh ? '关联仓库 · ' : 'Associated repository · ') : ''}${zh ? '近 7 天' : '7 days'} ${item.growthBasis === 'star_created' ? (zh ? '新增 Star' : 'new Stars') : (zh ? 'Star 净增' : 'net Star gain')}: ${item.gain > 0 ? '+' : ''}${num.format(item.gain)}`;
    return `<section style="border-top:1px solid #dedede;padding:20px 0"><h2 style="margin:0 0 8px;font-size:18px;overflow-wrap:anywhere"><a href="${escape(publicPath(locale, item))}" target="_blank" rel="noopener noreferrer" style="color:#111">${escape(item.full_name)}</a></h2><p style="margin:0;color:#606060">${escape(item.description)}</p>${metric ? `<p style="margin:10px 0 0;color:#315fd9;font-weight:700">${escape(metric)}</p>` : ''}${item.updatedAt ? `<p style="margin:8px 0 0;font-size:12px;color:#666">${zh ? '数据截至' : 'Sampled through'} ${escape(item.updatedAt.slice(0, 10))}</p>` : ''}${chartHtml}</section>`;
  }).join('');
  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f5f5f3;padding:16px"><main style="max-width:600px;margin:auto;padding:28px;background:#fff;color:#171717;font:15px/1.6 Arial,sans-serif">${emailBrandHeader('', locale)}<p style="text-align:center;color:#315fd9;font-size:12px;font-weight:700">${zh ? '示例邮件 · 公开目录内容' : 'SAMPLE EMAIL · PUBLIC CATALOG'}${discovery.source === 'demo' ? ' · DEMO DATA' : ''}</p><h1 style="font-size:24px;text-align:center">${zh ? '值得关注的开源变化' : 'Open-source changes worth a look'}</h1><p>${zh ? '这是格式预览，采用公开的近 7 天数据；实际每日摘要会按你的偏好生成。' : 'A format preview using public seven-day data. Your daily digest follows your preferences.'}</p>${rows || `<p>${zh ? '当前没有可预览的内容。' : 'No preview content is available.'}</p>`}<footer style="border-top:1px solid #dedede;padding-top:16px;color:#666;font-size:12px;text-align:center">${zh ? '每天最多一封 · 邮件启停可在 Settings 中管理' : 'At most one email a day · Manage email delivery in Settings'}</footer></main></body></html>`;
}
