import React, { useEffect, useState } from 'react';
import { DesignSelect } from './components.jsx';
import './billing.css';

const request = async (url, method = 'GET', body) => { const response = await fetch(url, { method, headers: body ? { 'Content-Type': 'application/json' } : {}, body: body ? JSON.stringify(body) : undefined }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || 'Request failed'); return result; };
const empty = { billing: { enabled: false, mode: 'test', currency: 'USD', weeklyPrice: 0, monthlyPrice: 0, weeklyProductId: '', monthlyProductId: '', apiBaseUrl: 'https://test-api.creem.io', graceDays: 3 }, contact: { email: '' }, social: { x: '', facebook: '', telegram: '' } };

export function AdminPage({ l }) {
  const zh = l === 'zh';
  const [admin, setAdmin] = useState(undefined), [token, setToken] = useState(''), [settings, setSettings] = useState(empty), [secrets, setSecrets] = useState({ creemApiKey: '', creemWebhookSecret: '' }), [flags, setFlags] = useState({}), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const load = async () => { try { await request('/api/admin/auth/me'); setAdmin(true); const data = await request('/api/admin/settings'); setSettings(data.settings); setFlags(data.secretFlags || {}); } catch { setAdmin(false); } };
  useEffect(() => { load(); }, []);
  const login = async event => { event.preventDefault(); setBusy(true); setMessage(''); try { await request('/api/admin/auth/login', 'POST', { token }); setToken(''); await load(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const save = async event => { event.preventDefault(); setBusy(true); setMessage(''); try { const payload = { ...settings, secrets: Object.fromEntries(Object.entries(secrets).filter(([, value]) => value)) }; const data = await request('/api/admin/settings', 'PUT', payload); setFlags(data.secretFlags); setSecrets({ creemApiKey: '', creemWebhookSecret: '' }); setMessage(zh ? '设置已保存。' : 'Settings saved.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const logout = async () => { await request('/api/admin/auth/logout', 'POST', {}); setAdmin(false); };
  const setBilling = (key, value) => setSettings(old => ({ ...old, billing: { ...old.billing, [key]: value } }));
  const setGroup = (group, key, value) => setSettings(old => ({ ...old, [group]: { ...old[group], [key]: value } }));
  if (admin === undefined) return <main className="admin-page"><p>{zh ? '加载中…' : 'Loading…'}</p></main>;
  if (!admin) return <main className="admin-page"><header><p className="billing-kicker">TREND TOP / ADMIN</p><h1>{zh ? '管理员登录' : 'Administrator sign in'}</h1><p>{zh ? '使用部署配置中的 ADMIN_TOKEN。' : 'Use the ADMIN_TOKEN from your deployment configuration.'}</p></header><form className="admin-login" onSubmit={login}><label>{zh ? '管理员令牌' : 'Administrator token'}<input type="password" value={token} onChange={event => setToken(event.target.value)} required autoComplete="current-password"/></label><button className="primary" disabled={busy}>{zh ? '登录' : 'Sign in'}</button>{message && <p role="alert">{message}</p>}</form></main>;
  return <main className="admin-page"><header><p className="billing-kicker">TREND TOP / ADMIN</p><h1>{zh ? '网站与账单设置' : 'Site and billing settings'}</h1><p>{zh ? '价格使用最小货币单位，例如 USD 900 表示 $9.00。敏感值保存时会加密。' : 'Prices use the smallest currency unit; USD 900 means $9.00. Secrets are encrypted when stored.'}</p><button type="button" className="ghost" onClick={logout}>{zh ? '退出管理员' : 'Sign out admin'}</button></header><form className="admin-settings" onSubmit={save}>
    <section><h2>Creem</h2><div className="admin-grid"><label><input type="checkbox" checked={settings.billing.enabled} onChange={event => setBilling('enabled', event.target.checked)}/> {zh ? '启用结账' : 'Enable checkout'}</label><label>{zh ? '模式' : 'Mode'}<DesignSelect value={settings.billing.mode} onChange={mode => { setBilling('mode', mode); setBilling('apiBaseUrl', mode === 'prod' ? 'https://api.creem.io' : 'https://test-api.creem.io'); }} options={['test','prod','sandbox'].map(value=>({value,label:value}))}/></label><label>{zh ? '币种' : 'Currency'}<input value={settings.billing.currency} maxLength="3" onChange={event => setBilling('currency', event.target.value)}/></label><label>{zh ? '周付金额' : 'Weekly price'}<input type="number" min="0" value={settings.billing.weeklyPrice} onChange={event => setBilling('weeklyPrice', Number(event.target.value))}/></label><label>{zh ? '月付金额' : 'Monthly price'}<input type="number" min="0" value={settings.billing.monthlyPrice} onChange={event => setBilling('monthlyPrice', Number(event.target.value))}/></label><label>{zh ? '周付产品 ID' : 'Weekly product ID'}<input value={settings.billing.weeklyProductId} onChange={event => setBilling('weeklyProductId', event.target.value)}/></label><label>{zh ? '月付产品 ID' : 'Monthly product ID'}<input value={settings.billing.monthlyProductId} onChange={event => setBilling('monthlyProductId', event.target.value)}/></label><label>API base URL<input type="url" value={settings.billing.apiBaseUrl} onChange={event => setBilling('apiBaseUrl', event.target.value)}/></label><label>{zh ? `API Key${flags.creemApiKey ? '（已保存）' : ''}` : `API key${flags.creemApiKey ? ' (saved)' : ''}`}<input type="password" value={secrets.creemApiKey} placeholder={flags.creemApiKey ? '••••••••' : ''} onChange={event => setSecrets(old => ({ ...old, creemApiKey: event.target.value }))}/></label><label>{zh ? `Webhook Secret${flags.creemWebhookSecret ? '（已保存）' : ''}` : `Webhook secret${flags.creemWebhookSecret ? ' (saved)' : ''}`}<input type="password" value={secrets.creemWebhookSecret} placeholder={flags.creemWebhookSecret ? '••••••••' : ''} onChange={event => setSecrets(old => ({ ...old, creemWebhookSecret: event.target.value }))}/></label></div></section>
    <section><h2>{zh ? '联系与社交' : 'Contact and social'}</h2><div className="admin-grid"><label>Gmail / Email<input type="email" value={settings.contact.email} onChange={event => setGroup('contact', 'email', event.target.value)}/></label>{['x','facebook','telegram'].map(key => <label key={key}>{key[0].toUpperCase() + key.slice(1)} URL<input type="url" value={settings.social[key]} onChange={event => setGroup('social', key, event.target.value)}/></label>)}</div></section>
    <button className="primary" disabled={busy}>{busy ? '…' : (zh ? '保存设置' : 'Save settings')}</button>{message && <p className="form-message" role="status">{message}</p>}
  </form></main>;
}
