import { pricingCache } from './pricing-data.js';
import React, { useEffect, useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { DesignSelect } from './components.jsx';
import { TYPES, typeLabel } from './catalog.js';
import { loginUrl } from '../shared/account-paths.js';
import './billing.css';

const request = async (url, method = 'GET', body) => { const response = await fetch(url, { method, headers: body ? { 'Content-Type': 'application/json' } : {}, body: body ? JSON.stringify(body) : undefined }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || 'Request failed'); return result; };
const emptyPrices = { en: { currency: 'USD', monthly: 0, yearly: 0 }, zh: { currency: 'CNY', monthly: 0, yearly: 0 } };
const empty = { authentication: { googleEnabled: false, googleClientId: '' }, billing: { enabled: false, mode: 'test', prices: emptyPrices, monthlyProductId: '', yearlyProductId: '', apiBaseUrl: 'https://test-api.creem.io', graceDays: 3 }, collection: { websiteEnrichment: true, firecrawlApiUrl: 'https://api.firecrawl.dev' }, contact: { email: '' }, social: { x: '', facebook: '', telegram: '' } };

function AdminDialog({ open, onOpenChange, kicker, title, children, actions }) {
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content admin-dialog"><p className="billing-kicker">{kicker}</p><Dialog.Title>{title}</Dialog.Title><Dialog.Description asChild><div className="admin-dialog-body">{children}</div></Dialog.Description><div className="admin-dialog-actions">{actions}</div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}

function AdminRefundRequests({ l }) {
  const zh = l === 'zh';
  const [items, setItems] = useState([]), [error, setError] = useState(''), [selected, setSelected] = useState(null), [note, setNote] = useState(''), [busy, setBusy] = useState(false);
  const load = async () => { try { const data = await request('/api/admin/refund-requests'); setItems(data.requests || []); setError(''); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, []);
  const review = async () => {
    setBusy(true); setError('');
    try { await request(`/api/admin/refund-requests/${selected.item.id}/review`, 'POST', { action: selected.action, note }); setSelected(null); setNote(''); await load(); }
    catch (e) { setError(e.message); }
    finally { setBusy(false); }
  };
  const statuses = zh ? { requested: '待审核', processing: '处理中', pending: '等待 Creem 确认', requires_action: '需要操作', succeeded: '退款成功', rejected: '已拒绝', failed: '退款失败', canceled: '已取消' } : { requested: 'Requested', processing: 'Processing', pending: 'Awaiting Creem', requires_action: 'Action required', succeeded: 'Refunded', rejected: 'Rejected', failed: 'Failed', canceled: 'Canceled' };
  return <section className="admin-refunds"><div className="billing-section-heading"><div><p className="billing-kicker">{zh ? '退款审核' : 'REFUND REVIEW'}</p><h2>{zh ? '退款申请' : 'Refund requests'}</h2></div><button className="ghost" type="button" onClick={load}>{zh ? '刷新' : 'Refresh'}</button></div><p className="admin-section-hint">{zh ? '批准会通过 Creem 退回该笔付款的剩余全额。待确认状态请在 Creem 查看，避免重复退款。' : 'Approval refunds the remaining payment in full through Creem. Check pending requests in Creem before taking further action.'}</p>{error && <p role="alert" className="billing-error">{error}</p>}{items.length === 0 ? <p>{zh ? '暂无退款申请。' : 'No refund requests.'}</p> : <ul className="refund-review-list">{items.map(item => <li key={item.id}><div><strong>{item.email}</strong><span>{new Intl.NumberFormat(l === 'zh' ? 'zh-CN' : 'en-US', { style: 'currency', currency: item.currency }).format(item.amount / 100)} · {statuses[item.status] || item.status}</span><p>{item.reason}</p>{item.adminNote && <p>{item.adminNote}</p>}</div>{item.status === 'requested' && <div className="billing-actions"><button className="ghost" onClick={() => { setSelected({ item, action: 'reject' }); setNote(''); }}>{zh ? '拒绝' : 'Reject'}</button><button className="primary" onClick={() => { setSelected({ item, action: 'approve' }); setNote(''); }}>{zh ? '审核退款' : 'Review refund'}</button></div>}</li>)}</ul>}<AdminDialog open={Boolean(selected)} onOpenChange={open => { if (!busy && !open) setSelected(null); }} kicker={zh ? '确认审核' : 'CONFIRM REVIEW'} title={selected?.action === 'approve' ? (zh ? '批准并执行退款？' : 'Approve and issue refund?') : (zh ? '拒绝此申请？' : 'Reject this request?')} actions={<><button className="ghost" disabled={busy} onClick={() => setSelected(null)}>{zh ? '返回' : 'Back'}</button><button className="primary" disabled={busy || (selected?.action === 'reject' && note.trim().length < 5)} onClick={review}>{busy ? '…' : (zh ? '确认' : 'Confirm')}</button></>}><p>{selected?.item.email}</p><p>{selected?.item.reason}</p><label className="refund-reason">{zh ? '审核备注（用户可见）' : 'Review note (visible to user)'}<textarea value={note} maxLength={1000} onChange={event => setNote(event.target.value)}/></label>{error && <p role="alert">{error}</p>}</AdminDialog></section>;
}

export function AdminPage({ l }) {
  const zh = l === 'zh';
  const [admin, setAdmin] = useState(undefined), [viewer, setViewer] = useState({ signedIn: false, email: '' }), [settings, setSettings] = useState(empty), [secrets, setSecrets] = useState({ googleClientSecret: '', creemApiKey: '', creemWebhookSecret: '', firecrawlApiKey: '' }), [flags, setFlags] = useState({}), [busy, setBusy] = useState(false);
  const [confirming, setConfirming] = useState(false), [result, setResult] = useState(null), [adminData, setAdminData] = useState(null);
  const [candidate, setCandidate] = useState({ url: '', type: 'website', notes: '' }), [candidateMessage, setCandidateMessage] = useState('');
  const [callbackUrl, setCallbackUrl] = useState('');
  const load = async () => { try { const me = await request('/api/admin/auth/me'); setViewer({ signedIn: Boolean(me.signedIn), email: me.email || '' }); if (!me.admin) { setAdmin(false); return; } const [data, operations] = await Promise.all([request('/api/admin/settings'), request('/api/admin')]); setSettings({ ...data.settings, billing: { ...data.settings.billing, prices: { ...emptyPrices, ...(data.settings.billing.prices || {}) } } }); setFlags(data.secretFlags || {}); setCallbackUrl(data.googleCallbackUrl || ''); setAdminData(operations); setAdmin(true); } catch { setAdmin(false); } };
  useEffect(() => { load(); }, []);
  const pendingSecrets = Object.entries(secrets).filter(([, value]) => value).map(([key]) => key);
  const save = async () => {
    setBusy(true);
    try { const payload = { ...settings, secrets: Object.fromEntries(Object.entries(secrets).filter(([, value]) => value)) }; const data = await request('/api/admin/settings', 'PUT', payload); pricingCache.clear(); setFlags(data.secretFlags); setSecrets({ googleClientSecret: '', creemApiKey: '', creemWebhookSecret: '', firecrawlApiKey: '' }); setSettings(old => ({ ...old, ...data.public })); setResult({ ok: true, at: new Date() }); }
    catch (error) { setResult({ ok: false, message: error.message }); }
    finally { setBusy(false); setConfirming(false); }
  };
  const setBilling = (key, value) => setSettings(old => ({ ...old, billing: { ...old.billing, [key]: value } }));
  const setPrice = (locale, key, value) => setSettings(old => ({ ...old, billing: { ...old.billing, prices: { ...old.billing.prices, [locale]: { ...old.billing.prices[locale], [key]: value } } } }));
  const setGroup = (group, key, value) => setSettings(old => ({ ...old, [group]: { ...old[group], [key]: value } }));
  const submitCandidate = async event => {
    event.preventDefault();setCandidateMessage('');
    try { const data = await request('/api/admin/candidates', 'POST', candidate); setCandidate({ url: '', type: 'website', notes: '' }); setCandidateMessage(zh ? '候选已加入审核队列。' : 'Candidate added to the review queue.'); setAdminData(old => old ? { ...old, candidates: [data.candidate, ...(old.candidates || []).filter(item => item.id !== data.candidate.id)] } : old); }
    catch (error) { setCandidateMessage(error.message); }
  };
  if (admin === undefined) return <main className="admin-page"><p>{zh ? '加载中…' : 'Loading…'}</p></main>;
  if (!admin) return <main className="admin-page"><header><p className="billing-kicker">TREND TOP / ADMIN</p><h1>{zh ? '仅限管理员' : 'Administrators only'}</h1><p>{viewer.signedIn ? (zh ? `当前账户 ${viewer.email} 不是管理员。` : `The account ${viewer.email} is not an administrator.`) : (zh ? '请先用管理员账户登录，再打开此页。' : 'Sign in with an administrator account to open this page.')}</p></header><div className="admin-login"><a className="primary billing-link" href={viewer.signedIn ? `/${l}/account` : loginUrl(l, `/${l}/admin`)}>{viewer.signedIn ? (zh ? '账户设置' : 'Account settings') : (zh ? '前往登录' : 'Go to sign in')}</a></div></main>;
  const priceFields = (locale, title, hint) => <section key={locale}><h2>{title}</h2><p className="admin-section-hint">{hint}</p><div className="admin-grid admin-grid-3"><label>{zh ? '币种' : 'Currency'}<input value={settings.billing.prices[locale].currency} maxLength="3" pattern="[A-Za-z]{3}" onChange={event => setPrice(locale, 'currency', event.target.value.toUpperCase())}/></label><label>{zh ? '月付价格' : 'Monthly price'}<input type="number" min="0" step="0.01" inputMode="decimal" value={settings.billing.prices[locale].monthly} onChange={event => setPrice(locale, 'monthly', event.target.value)}/></label><label>{zh ? '年付价格' : 'Yearly price'}<input type="number" min="0" step="0.01" inputMode="decimal" value={settings.billing.prices[locale].yearly} onChange={event => setPrice(locale, 'yearly', event.target.value)}/></label></div></section>;
  return <main className="admin-page"><header><p className="billing-kicker">TREND TOP / ADMIN</p><h1>{zh ? '网站与账单设置' : 'Site and billing settings'}</h1><p>{zh ? '价格按主单位填写，支持两位小数（如 9.99），英文站和中文站分别设置。实际扣款以 Creem 产品价格为准，请保持一致。敏感值保存时会加密。' : 'Enter prices in major units with up to two decimals (for example 9.99), separately for the English and Chinese sites. Creem charges the product price, so keep them in sync. Secrets are encrypted when stored.'}</p><p className="admin-viewer">{zh ? `管理员：${viewer.email}` : `Administrator: ${viewer.email}`}</p></header><form className="admin-settings" onSubmit={event => { event.preventDefault(); setConfirming(true); }}>
    <section><h2>Creem</h2><div className="admin-grid"><label><input type="checkbox" checked={settings.billing.enabled} onChange={event => setBilling('enabled', event.target.checked)}/> {zh ? '启用结账' : 'Enable checkout'}</label><label>{zh ? '模式' : 'Mode'}<DesignSelect value={settings.billing.mode} onChange={mode => { setBilling('mode', mode); setBilling('apiBaseUrl', mode === 'prod' ? 'https://api.creem.io' : 'https://test-api.creem.io'); }} options={['test','prod','sandbox'].map(value=>({value,label:value}))}/></label><label>{zh ? '月付产品 ID' : 'Monthly product ID'}<input value={settings.billing.monthlyProductId} onChange={event => setBilling('monthlyProductId', event.target.value)}/></label><label>{zh ? '年付产品 ID' : 'Yearly product ID'}<input value={settings.billing.yearlyProductId} onChange={event => setBilling('yearlyProductId', event.target.value)}/></label><label>API base URL<input type="url" value={settings.billing.apiBaseUrl} onChange={event => setBilling('apiBaseUrl', event.target.value)}/></label><label>{zh ? '宽限天数' : 'Grace days'}<input type="number" min="0" max="30" value={settings.billing.graceDays} onChange={event => setBilling('graceDays', Number(event.target.value))}/></label><label>{zh ? `API Key${flags.creemApiKey ? '（已保存）' : ''}` : `API key${flags.creemApiKey ? ' (saved)' : ''}`}<input type="password" value={secrets.creemApiKey} placeholder={flags.creemApiKey ? '••••••••' : ''} onChange={event => setSecrets(old => ({ ...old, creemApiKey: event.target.value }))}/></label><label>{zh ? `Webhook Secret${flags.creemWebhookSecret ? '（已保存）' : ''}` : `Webhook secret${flags.creemWebhookSecret ? ' (saved)' : ''}`}<input type="password" value={secrets.creemWebhookSecret} placeholder={flags.creemWebhookSecret ? '••••••••' : ''} onChange={event => setSecrets(old => ({ ...old, creemWebhookSecret: event.target.value }))}/></label></div></section>
    <section><h2>Google {zh ? '登录' : 'sign in'}</h2><p className="admin-section-hint">{zh ? '在 Google Cloud 创建 Web OAuth 客户端，并将下方回调地址加入授权重定向 URI。保存 Client ID 和 Secret 后启用。仅用于验证身份，不读取 Gmail 邮件。' : 'Create a Web OAuth client in Google Cloud and add the callback below as an authorized redirect URI. Save its Client ID and Secret, then enable sign in. This verifies identity without accessing Gmail.'}</p><div className="admin-grid"><label><input type="checkbox" checked={Boolean(settings.authentication?.googleEnabled)} onChange={event => setGroup('authentication', 'googleEnabled', event.target.checked)}/>{zh ? '启用 Google 登录' : 'Enable Google sign in'}</label><label>Client ID<input value={settings.authentication?.googleClientId || ''} onChange={event => setGroup('authentication', 'googleClientId', event.target.value)}/></label><label>{`Client Secret${flags.googleClientSecret ? (zh ? '（已保存）' : ' (saved)') : ''}`}<input type="password" autoComplete="new-password" value={secrets.googleClientSecret || ''} placeholder={flags.googleClientSecret ? '••••••••' : ''} onChange={event => setSecrets(old => ({ ...old, googleClientSecret: event.target.value }))}/></label><label>{zh ? '授权回调地址' : 'Authorized callback URL'}<input value={callbackUrl} readOnly/></label></div></section>
    {priceFields('en', zh ? '英文站价格' : 'English site prices', zh ? '显示在 /en/pricing。默认 USD。' : 'Shown on /en/pricing. USD by default.')}
    {priceFields('zh', zh ? '中文站价格' : 'Chinese site prices', zh ? '显示在 /zh/pricing。默认 CNY。' : 'Shown on /zh/pricing. CNY by default.')}
    <section><h2>{zh ? 'Website 数据采集' : 'Website collection'}</h2><p className="admin-section-hint">{zh ? '来源注册表会定时读取独立网站。配置 Firecrawl 后优先使用页面抽取，未配置时使用受限的直接元数据读取。' : 'The source registry refreshes independent websites. Firecrawl is preferred when configured; a limited direct metadata fetch is used otherwise.'}</p><div className="admin-grid"><label><input type="checkbox" checked={settings.collection?.websiteEnrichment !== false} onChange={event => setGroup('collection', 'websiteEnrichment', event.target.checked)}/> {zh ? '启用 Website 页面补充采集' : 'Enable Website page enrichment'}</label><label>Firecrawl API URL<input type="url" value={settings.collection?.firecrawlApiUrl || ''} onChange={event => setGroup('collection', 'firecrawlApiUrl', event.target.value)}/></label><label>{zh ? `Firecrawl API Key${flags.firecrawlApiKey ? '（已保存）' : ''}` : `Firecrawl API key${flags.firecrawlApiKey ? ' (saved)' : ''}`}<input type="password" value={secrets.firecrawlApiKey} placeholder={flags.firecrawlApiKey ? '••••••••' : ''} onChange={event => setSecrets(old => ({ ...old, firecrawlApiKey: event.target.value }))}/></label></div></section>
    <section><h2>{zh ? '联系与社交' : 'Contact and social'}</h2><div className="admin-grid"><label>Gmail / Email<input type="email" value={settings.contact.email} onChange={event => setGroup('contact', 'email', event.target.value)}/></label>{['x','facebook','telegram'].map(key => <label key={key}>{key[0].toUpperCase() + key.slice(1)} URL<input type="url" value={settings.social[key]} onChange={event => setGroup('social', key, event.target.value)}/></label>)}</div></section>
    <button className="primary" disabled={busy}>{busy ? '…' : (zh ? '保存设置' : 'Save settings')}</button>
  </form>
  <AdminRefundRequests l={l}/>
  <section className="admin-operations"><div><p className="billing-kicker">{zh ? '采集运营' : 'COLLECTION OPERATIONS'}</p><h2>{zh ? '来源与候选' : 'Sources and candidates'}</h2><p className="admin-section-hint">{zh ? '手动候选用于修正规则盲区；自动采集仍由固定配额查询和 Website 来源注册表完成。' : 'Manual candidates cover rule gaps; fixed-quota discovery and the Website source registry remain the primary collectors.'}</p></div><form className="admin-candidate-form" onSubmit={submitCandidate}><label>{zh ? '候选 URL' : 'Candidate URL'}<input type="url" required value={candidate.url} onChange={event => setCandidate(old => ({ ...old, url: event.target.value }))}/></label><label>{zh ? '类型' : 'Type'}<DesignSelect value={candidate.type} onChange={type => setCandidate(old => ({ ...old, type }))} options={TYPES.map(type => ({ value: type, label: typeLabel(type, l) }))}/></label><label className="admin-candidate-notes">{zh ? '备注' : 'Notes'}<input value={candidate.notes} maxLength="500" onChange={event => setCandidate(old => ({ ...old, notes: event.target.value }))}/></label><button className="primary">{zh ? '加入候选' : 'Add candidate'}</button></form>{candidateMessage && <p role="status">{candidateMessage}</p>}<div className="admin-collection-grid"><article><strong>{adminData?.sources?.length || 0}</strong><span>{zh ? 'Website 来源' : 'Website sources'}</span></article><article><strong>{adminData?.candidates?.filter(item => item.status === 'pending').length || 0}</strong><span>{zh ? '待审核候选' : 'Pending candidates'}</span></article><article><strong>{adminData?.queryStats?.length || 0}</strong><span>{zh ? '近期查询记录' : 'Recent query records'}</span></article></div>{adminData?.queryStats?.length > 0 && <div className="admin-query-table" role="region" aria-label={zh ? '查询采集统计' : 'Query collection statistics'}><table><thead><tr><th>{zh ? '类型' : 'Type'}</th><th>{zh ? '查询组' : 'Family'}</th><th>{zh ? '返回' : 'Returned'}</th><th>{zh ? '采纳' : 'Accepted'}</th><th>{zh ? '状态' : 'Status'}</th></tr></thead><tbody>{adminData.queryStats.slice(0, 20).map(row => <tr key={row.id}><td>{row.collection_type}</td><td title={row.query_text}>{row.family}</td><td>{row.returned}</td><td>{row.accepted}</td><td>{row.error ? (zh ? '失败' : 'Failed') : (zh ? '完成' : 'OK')}</td></tr>)}</tbody></table></div>}</section>
  <AdminDialog open={confirming} onOpenChange={open => { if (!busy) setConfirming(open); }} kicker={zh ? '确认保存' : 'CONFIRM SAVE'} title={zh ? '保存这些设置？' : 'Save these settings?'} actions={<><button type="button" className="ghost" disabled={busy} onClick={() => setConfirming(false)}>{zh ? '取消' : 'Cancel'}</button><button type="button" className="primary" disabled={busy} onClick={save}>{busy ? (zh ? '保存中…' : 'Saving…') : (zh ? '确认保存' : 'Save')}</button></>}>
    <p>{zh ? '保存后立即生效，价格页和页脚会随之更新。' : 'Changes take effect immediately on the pricing page and footer.'}</p>
    <ul><li>{zh ? '结账：' : 'Checkout: '}{settings.billing.enabled ? (zh ? '启用' : 'enabled') : (zh ? '关闭' : 'disabled')} · {settings.billing.mode}</li><li>/en: {settings.billing.prices.en.currency} {settings.billing.prices.en.monthly || 0} / {zh ? '月' : 'month'}, {settings.billing.prices.en.yearly || 0} / {zh ? '年' : 'year'}</li><li>/zh: {settings.billing.prices.zh.currency} {settings.billing.prices.zh.monthly || 0} / {zh ? '月' : 'month'}, {settings.billing.prices.zh.yearly || 0} / {zh ? '年' : 'year'}</li>{pendingSecrets.length > 0 && <li>{zh ? '将更新密钥：' : 'Secrets to update: '}{pendingSecrets.join(', ')}</li>}</ul>
  </AdminDialog>
  <AdminDialog open={Boolean(result)} onOpenChange={open => { if (!open) setResult(null); }} kicker={result?.ok ? (zh ? '已保存' : 'SAVED') : (zh ? '保存失败' : 'SAVE FAILED')} title={result?.ok ? (zh ? '设置已保存' : 'Settings saved') : (zh ? '设置未保存' : 'Settings were not saved')} actions={<button type="button" className="primary" onClick={() => setResult(null)}>{zh ? '关闭' : 'Close'}</button>}>
    <p className={result?.ok ? 'admin-result-ok' : 'admin-result-error'}><span aria-hidden="true">{result?.ok ? '✓' : '!'}</span>{result?.ok ? (zh ? `已于 ${result.at.toLocaleTimeString(zh ? 'zh-CN' : 'en-US')} 写入数据库。` : `Written to the database at ${result.at.toLocaleTimeString('en-US')}.`) : result?.message}</p>
  </AdminDialog>
  </main>;
}
