import React, { useEffect, useState } from 'react';
import { loginUrl } from '../shared/account-paths.js';
import { normalizeSavedFilters, savedSearchPath } from '../shared/saved-search-filters.js';
import { typeLabel } from './catalog.js';
const request=async(url,method='GET',body)=>{const response=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error),{status:response.status});return data};
export function SaveSearchButton({l,filters,user,proActive}){
  const zh=l==='zh',[open,setOpen]=useState(false),[name,setName]=useState(''),[notify,setNotify]=useState(false),[rule,setRule]=useState('new-entry'),[threshold,setThreshold]=useState(10),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  return <div className="save-search-control" onKeyDown={event=>{if(event.key==='Escape')setOpen(false)}}><button type="button" className="primary" aria-expanded={open} onClick={()=>{if(!user){location.assign(loginUrl(l,location.pathname+location.search));return}if(proActive===false){location.assign(`/${l}/pricing`);return}setOpen(value=>!value)}}>{zh?'保存筛选':'Save filters'}</button>{open&&<form className="saved-search-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setMessage('');try{await request('/api/saved-searches','POST',{name,filters:normalizeSavedFilters(filters),notify,rule,threshold});setMessage(zh?'已保存，可在账户的保存筛选中管理。':'Saved. Manage it in your account’s Saved searches.');setOpen(false)}catch(error){setMessage(error.status===403?(zh?'保存筛选需要 Pro。':'Pro is required to save filters.'):zh?'保存失败，请重试。':'Could not save. Try again.')}finally{setBusy(false)}}}>
    <label>{zh?'名称':'Name'}<input value={name} onChange={event=>setName(event.target.value)} maxLength="100" required/></label><label className="saved-search-check"><input type="checkbox" checked={notify} onChange={event=>setNotify(event.target.checked)}/>{zh?'在每日摘要中提醒变化':'Include changes in the daily digest'}</label>
    {notify&&<><label>{zh?'提醒规则':'Change rule'}<select value={rule} onChange={event=>setRule(event.target.value)}><option value="new-entry">{zh?'首次进入结果':'New entry in results'}</option><option value="growth-threshold">{zh?'窗口增量达到阈值':'Window growth reaches threshold'}</option></select></label>{rule==='growth-threshold'&&<label>{zh?'新增 Star 至少':'At least this many new stars'}<input type="number" min="1" max="1000000" value={threshold} onChange={event=>setThreshold(event.target.value)}/></label>}<p className="muted">{zh?'每日采集后，在已开启的摘要中每天最多提醒一次。首封建立比较基线，最多检查前 50 个结果。':'Checked after daily collection, at most once per daily digest when emails are enabled. The first digest establishes a baseline; up to 50 results are checked.'}</p></>}
    <div className="repo-tags"><button className="primary" disabled={busy}>{zh?'保存':'Save'}</button><button type="button" className="ghost" onClick={()=>setOpen(false)}>{zh?'取消':'Cancel'}</button></div></form>}{message&&<p role="status">{message}</p>}</div>;
}
export function SavedSearchPanel({l,proActive,navigate}){
  const zh=l==='zh',[items,setItems]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState('');
  const load=()=>request('/api/saved-searches').then(data=>setItems(data.items)).catch(()=>setMessage(zh?'加载失败，请重试。':'Could not load. Try again.'));
  useEffect(()=>{load()},[]);
  const update=async(item,remove=false,changes=null)=>{setBusy(item.id);setMessage('');try{await request(`/api/saved-searches/${item.id}`,remove?'DELETE':'PUT',remove?{}:{...item,...(changes || {notify:!item.notify})});await load()}catch{setMessage(zh?'操作失败，请重试。':'Could not update. Try again.')}finally{setBusy('')}};
  return <section className="saved-search-panel"><h2>{zh?'保存的筛选':'Saved searches'}</h2><p>{zh?'保留常用筛选。变化提醒会合并到每日摘要，停止邮件不会取消 Pro。':'Keep your useful filters. Change alerts join your daily digest. Stopping emails does not cancel Pro.'}</p>{!proActive&&<p>{zh?'重新成为 Pro 后可编辑提醒；已保存的筛选仍可打开或删除。':'Reactivate Pro to edit alerts. You can still open or delete saved searches.'}</p>}{items?.length===0&&<p>{zh?'在 Rankings 中选好条件后，点击“保存筛选”。':'Choose filters on Rankings, then select “Save filters”.'}</p>}{items?.map(item=><article className="saved-search-card" key={item.id}><h3><a href={savedSearchPath(l,item.filters)} onClick={event=>{if(event.button!==0||event.metaKey||event.ctrlKey)return;event.preventDefault();navigate(savedSearchPath(l,item.filters))}}>{item.name}</a></h3><p>{typeLabel(item.filters.type,l)} · {item.filters.board} · {item.filters.period}{item.filters.topic?` · ${item.filters.topic}`:''}{item.filters.useCase?` · ${item.filters.useCase}`:''}{item.filters.language?` · ${item.filters.language}`:''}</p><p>{item.notify?(zh?'每日变化提醒开启':'Daily change alerts on'):(zh?'变化提醒关闭':'Change alerts off')} · {item.rule==='growth-threshold'?`${zh?'窗口新增 Star ≥':'Window star growth ≥'} ${item.threshold}`:(zh?'新进入结果':'New entry in results')}</p><div className="repo-tags"><button type="button" className="ghost" disabled={!proActive||busy===item.id} onClick={()=>update(item)}>{item.notify?(zh?'关闭提醒':'Turn alerts off'):(zh?'开启提醒':'Turn alerts on')}</button><button type="button" className="ghost" disabled={busy===item.id} onClick={()=>update(item,true)}>{zh?'删除':'Delete'}</button></div>{proActive&&<details><summary>{zh?'编辑名称与提醒规则':'Edit name and alert rule'}</summary><form className="saved-search-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);update(item,false,{name:form.get('name'),notify:form.get('notify')==='on',rule:form.get('rule'),threshold:Number(form.get('threshold'))})}}><label>{zh?'名称':'Name'}<input name="name" defaultValue={item.name} maxLength="100" required/></label><label className="saved-search-check"><input name="notify" type="checkbox" defaultChecked={item.notify}/>{zh?'每日提醒':'Daily alerts'}</label><label>{zh?'提醒规则':'Alert rule'}<select name="rule" defaultValue={item.rule}><option value="new-entry">{zh?'新进入结果':'New entry in results'}</option><option value="growth-threshold">{zh?'增长达到阈值':'Growth reaches threshold'}</option></select></label><label>{zh?'新增 Star 阈值':'New-star threshold'}<input name="threshold" type="number" min="1" max="1000000" defaultValue={item.threshold}/></label><button className="primary" disabled={busy===item.id}>{zh?'保存修改':'Save changes'}</button></form></details>}</article>)}{message&&<p role="status">{message}</p>}{items===null&&<button type="button" className="ghost" onClick={load}>{zh?'加载 / 重试':'Load / retry'}</button>}</section>;
}
export function DeliveryHistory({l}){
  const zh=l==='zh',[items,setItems]=useState(null),[message,setMessage]=useState(''),[notes,setNotes]=useState('');
  useEffect(()=>{request('/api/delivery-history').then(data=>setItems(data.items)).catch(()=>setMessage(zh?'暂时无法读取发送记录。':'Send history is temporarily unavailable.'))},[]);
  const labels={sent:zh?'服务商已接收':'Accepted by provider',pending:zh?'等待发送':'Pending',sending:zh?'正在提交':'Submitting',failed:zh?'发送失败':'Failed',uncertain:zh?'正在核对':'Under review',skipped:zh?'未发送':'Not sent'};
  return <section className="delivery-history"><h2>{zh?'最近发送记录':'Recent sends'}</h2><p className="muted">{zh?'服务商接收不等于已进入收件箱；这里只展示我们能确认的状态。':'Provider acceptance does not confirm inbox delivery. These are the states we can verify.'}</p>{items?.length===0&&<p>{zh?'暂无发送记录。':'No send history yet.'}</p>}<ul>{items?.map(item=><li key={item.id}><span>{item.local_date}</span><span className="source-tag">{labels[item.status] || item.status}</span></li>)}</ul><form onSubmit={async event=>{event.preventDefault();const rating=event.nativeEvent.submitter?.value;try{await request('/api/feedback','POST',{rating,notes,deliveryId:items?.find(item=>item.status==='sent')?.id});setMessage(zh?'谢谢，反馈已记录。':'Thank you. Your feedback is recorded.');setNotes('')}catch{setMessage(zh?'提交失败，请重试。':'Could not submit. Try again.')}}}><label>{zh?'摘要反馈（可选）':'Digest feedback (optional)'}<textarea maxLength="1000" value={notes} onChange={event=>setNotes(event.target.value)}/></label><div className="repo-tags"><button className="ghost" name="rating" value="useful">{zh?'有帮助':'Useful'}</button><button className="ghost" name="rating" value="not-relevant">{zh?'内容不相关':'Not relevant'}</button><button className="ghost" name="rating" value="unreliable">{zh?'数据有问题':'Data issue'}</button></div></form>{message&&<p role="status">{message}</p>}</section>;
}
